Modifications for API lib only configuration and build.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os LDFLAGS CFLAGS FFLAGS BINUTILS_DIR BIN_TYPE_FLAG DISABLE_MPI_IO ENABLE_FORTRAN_XLATE STACKDEPTH USE_LIBDWARF USE_GETARG DO_DEMANGLE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA RANLIB ac_ct_RANLIB CC CXX F77 LAUNCH CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP READ_REAL_TIME ac_ct_F77 FORTRAN_GETARG F77_SYMBOLS F77_VENDOR MPIPFLIB FORTRAN_FLAG FORTRAN_TARGET LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os LDFLAGS CFLAGS FFLAGS BINUTILS_DIR BIN_TYPE_FLAG ENABLE_API_ONLY DISABLE_MPI_IO ENABLE_FORTRAN_XLATE STACKDEPTH USE_LIBDWARF USE_GETARG DO_DEMANGLE INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA RANLIB ac_ct_RANLIB CC CXX F77 LAUNCH CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP READ_REAL_TIME ac_ct_F77 FORTRAN_GETARG F77_SYMBOLS F77_VENDOR MPIPFLIB FORTRAN_FLAG FORTRAN_TARGET LIBOBJS LTLIBOBJS'
 ac_subst_files='HAVE_MPI_IO'
 
 # Initialize some variables set by options.
@@ -857,6 +857,7 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-api-only       Only build the API library.
   --disable-mpi-io        Disable MPI-I/O reporting.
   --disable-bfd           Do not use GNU binutils libbfd for source lookup.
   --disable-libunwind     Do not use libunwind to generate stack traces.
@@ -1579,6 +1580,25 @@ fi;
 #  Enable / Disable specifications
 #
 
+ENABLE_API_ONLY=no
+# Check whether --enable-api-only or --disable-api-only was given.
+if test "${enable_api_only+set}" = set; then
+  enableval="$enable_api_only"
+  if test x"$enableval" = xyes ; then
+		ENABLE_API_ONLY=yes
+		echo Configuring for API library only.
+               	cat >>confdefs.h <<\_ACEOF
+#define ENABLE_API_ONLY 1
+_ACEOF
+
+	fi
+
+fi;
+
+
+
+if test "$ENABLE_API_ONLY" = no ; then
+
 DISABLE_MPI_IO=no
 # Check whether --enable-mpi-io or --disable-mpi-io was given.
 if test "${enable_mpi_io+set}" = set; then
@@ -1590,6 +1610,7 @@ if test "${enable_mpi_io+set}" = set; then
 
 fi;
 
+fi
 
 DISABLE_BFD=no
 # Check whether --enable-bfd or --disable-bfd was given.
@@ -1866,7 +1887,8 @@ else
   RANLIB="$ac_cv_prog_RANLIB"
 fi
 
-for ac_prog in mpcc_r xlc_r mpicc cmpicc gcc cc icc
+if test "$ENABLE_API_ONLY" = no ; then
+  for ac_prog in mpcc_r xlc_r mpicc cmpicc gcc cc icc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -1907,7 +1929,7 @@ fi
 done
 test -n "$CC" || CC="mpicc"
 
-for ac_prog in mpCC_r xlC_r mpiCC mpicxx cmpic++ c++ g++ CC cxx icc
+  for ac_prog in mpCC_r xlC_r mpiCC mpicxx cmpic++ c++ g++ CC cxx icc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -1948,7 +1970,7 @@ fi
 done
 test -n "$CXX" || CXX="mpiCC"
 
-for ac_prog in mpxlf_r xlf_r mpif77 cmpifc f77 g77 pgf77 fort ifc
+  for ac_prog in mpxlf_r xlf_r mpif77 cmpifc f77 g77 pgf77 fort ifc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -1989,7 +2011,7 @@ fi
 done
 test -n "$F77" || F77="mpif77"
 
-for ac_prog in poe srun prun mpirun
+  for ac_prog in poe srun prun mpirun
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -2030,6 +2052,132 @@ fi
 done
 test -n "$LAUNCH" || LAUNCH="mpirun"
 
+else
+  for ac_prog in gcc cc icc
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_CC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$CC"; then
+  ac_cv_prog_CC="$CC" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_CC="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+CC=$ac_cv_prog_CC
+if test -n "$CC"; then
+  echo "$as_me:$LINENO: result: $CC" >&5
+echo "${ECHO_T}$CC" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$CC" && break
+done
+test -n "$CC" || CC="mpicc"
+
+  for ac_prog in c++ g++ CC cxx icc
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_CXX+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$CXX"; then
+  ac_cv_prog_CXX="$CXX" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_CXX="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+CXX=$ac_cv_prog_CXX
+if test -n "$CXX"; then
+  echo "$as_me:$LINENO: result: $CXX" >&5
+echo "${ECHO_T}$CXX" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$CXX" && break
+done
+test -n "$CXX" || CXX="mpiCC"
+
+  for ac_prog in f77 g77 pgf77 fort ifc
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_F77+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$F77"; then
+  ac_cv_prog_F77="$F77" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_F77="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+F77=$ac_cv_prog_F77
+if test -n "$F77"; then
+  echo "$as_me:$LINENO: result: $F77" >&5
+echo "${ECHO_T}$F77" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$F77" && break
+done
+test -n "$F77" || F77="mpif77"
+
+  LAUNCH=""
+fi
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -3038,7 +3186,7 @@ fi
 
 
 if test "$DISABLE_BFD" = "no" ; then
-ac_ext=c
+  ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -3819,7 +3967,7 @@ _ACEOF
 
 fi
 
-if test "${ac_cv_header_bfd_h+set}" = set; then
+  if test "${ac_cv_header_bfd_h+set}" = set; then
   echo "$as_me:$LINENO: checking for bfd.h" >&5
 echo $ECHO_N "checking for bfd.h... $ECHO_C" >&6
 if test "${ac_cv_header_bfd_h+set}" = set; then
@@ -4100,8 +4248,76 @@ fi
 fi
 
 
+  echo "$as_me:$LINENO: checking for bfd_boolean" >&5
+echo $ECHO_N "checking for bfd_boolean... $ECHO_C" >&6
+if test "${ac_cv_type_bfd_boolean+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "bfd.h"
 
-echo "$as_me:$LINENO: checking for MPIR_ToPointer in -lmpi" >&5
+int
+main ()
+{
+if ((bfd_boolean *) 0)
+  return 0;
+if (sizeof (bfd_boolean))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_bfd_boolean=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_bfd_boolean=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_bfd_boolean" >&5
+echo "${ECHO_T}$ac_cv_type_bfd_boolean" >&6
+if test $ac_cv_type_bfd_boolean = yes; then
+  :
+else
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_BFD_BOOLEAN 1
+_ACEOF
+
+fi
+
+fi
+
+if test "$ENABLE_API_ONLY" = no ; then
+  echo "$as_me:$LINENO: checking for MPIR_ToPointer in -lmpi" >&5
 echo $ECHO_N "checking for MPIR_ToPointer in -lmpi... $ECHO_C" >&6
 if test "${ac_cv_lib_mpi_MPIR_ToPointer+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -4172,7 +4388,7 @@ _ACEOF
 
 fi
 
-echo "$as_me:$LINENO: checking for MPIR_ToPointer in -lmpich" >&5
+  echo "$as_me:$LINENO: checking for MPIR_ToPointer in -lmpich" >&5
 echo $ECHO_N "checking for MPIR_ToPointer in -lmpich... $ECHO_C" >&6
 if test "${ac_cv_lib_mpich_MPIR_ToPointer+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -4239,73 +4455,6 @@ echo "${ECHO_T}$ac_cv_lib_mpich_MPIR_ToPointer" >&6
 if test $ac_cv_lib_mpich_MPIR_ToPointer = yes; then
   cat >>confdefs.h <<\_ACEOF
 #define HAVE_MPIR_TOPOINTER 1
-_ACEOF
-
-fi
-
-
-echo "$as_me:$LINENO: checking for bfd_boolean" >&5
-echo $ECHO_N "checking for bfd_boolean... $ECHO_C" >&6
-if test "${ac_cv_type_bfd_boolean+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include "bfd.h"
-
-int
-main ()
-{
-if ((bfd_boolean *) 0)
-  return 0;
-if (sizeof (bfd_boolean))
-  return 0;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_type_bfd_boolean=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_type_bfd_boolean=no
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-fi
-echo "$as_me:$LINENO: result: $ac_cv_type_bfd_boolean" >&5
-echo "${ECHO_T}$ac_cv_type_bfd_boolean" >&6
-if test $ac_cv_type_bfd_boolean = yes; then
-  :
-else
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_BFD_BOOLEAN 1
 _ACEOF
 
 fi
@@ -4537,7 +4686,7 @@ fi
 
 fi
 
-if test "$DISABLE_MPI_IO" = no ; then
+if test "$ENABLE_API_ONLY" = no && test "$DISABLE_MPI_IO" = no ; then
 echo "$as_me:$LINENO: checking for MPI_File_open" >&5
 echo $ECHO_N "checking for MPI_File_open... $ECHO_C" >&6
 if test "${ac_cv_func_MPI_File_open+set}" = set; then
@@ -4815,6 +4964,8 @@ fi
 
 
 
+if test "$ENABLE_API_ONLY" = no ; then
+
 if test "$ENABLE_FORTRAN_XLATE" = yes ; then
      echo "$as_me:$LINENO: checking fortran to C conversion" >&5
 echo $ECHO_N "checking fortran to C conversion... $ECHO_C" >&6
@@ -4867,6 +5018,7 @@ echo "${ECHO_T}functions not found  translation deactivated" >&6
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+fi
 fi
 
 #  If using Fortran routines to access command line,
@@ -4972,7 +5124,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4975:" \
+echo "$as_me:5127:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5207,6 +5359,7 @@ fi
 
 
 
+if test "$ENABLE_API_ONLY" = no ; then
 
 echo "$as_me:$LINENO: checking fortran symbols" >&5
 echo $ECHO_N "checking fortran symbols... $ECHO_C" >&6
@@ -5303,6 +5456,7 @@ else
   FORTRAN_FLAG=
   FORTRAN_TARGET=
 fi
+fi #if test "$ENABLE_API_ONLY" = no ; then
 
 echo "$as_me:$LINENO: result: $F77_VENDOR" >&5
 echo "${ECHO_T}$F77_VENDOR" >&6
@@ -5899,6 +6053,7 @@ s,@CFLAGS@,$CFLAGS,;t t
 s,@FFLAGS@,$FFLAGS,;t t
 s,@BINUTILS_DIR@,$BINUTILS_DIR,;t t
 s,@BIN_TYPE_FLAG@,$BIN_TYPE_FLAG,;t t
+s,@ENABLE_API_ONLY@,$ENABLE_API_ONLY,;t t
 s,@DISABLE_MPI_IO@,$DISABLE_MPI_IO,;t t
 s,@ENABLE_FORTRAN_XLATE@,$ENABLE_FORTRAN_XLATE,;t t
 s,@STACKDEPTH@,$STACKDEPTH,;t t
