consistency

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -3608,7 +3608,7 @@ if test "${ac_cv_lib_bfd_bfd_openr+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lbfd -lintl -liberty $LIBS"
+LIBS="-lbfd  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -3667,6 +3667,64 @@ fi
 
 fi
 
+
+echo "$as_me:$LINENO: checking for bfd_boolean" >&5
+echo $ECHO_N "checking for bfd_boolean... $ECHO_C" >&6
+if test "${ac_cv_type_bfd_boolean+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "bfd.h"
+
+
+int
+main ()
+{
+if ((bfd_boolean *) 0)
+  return 0;
+if (sizeof (bfd_boolean))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_bfd_boolean=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_bfd_boolean=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_bfd_boolean" >&5
+echo "${ECHO_T}$ac_cv_type_bfd_boolean" >&6
+if test $ac_cv_type_bfd_boolean = yes; then
+  :
+else
+  cat >>confdefs.h <<\_ACEOF
+#define BFD_TRUE_FALSE 1
+_ACEOF
+
+fi
 
 if test -z "$DISABLE_LIBUNWIND" ; then
 if test "${ac_cv_header_libunwind_h+set}" = set; then
@@ -3885,8 +3943,8 @@ if test $ac_cv_func_MPI_File_open = yes; then
 _ACEOF
  HAVE_MPI_IO=mpi.io.protos.txt
 else
-  echo "$as_me:$LINENO: result: \"MPI I/O symbols not found.  MPI I/O reporting deactivated.\"" >&5
-echo "${ECHO_T}\"MPI I/O symbols not found.  MPI I/O reporting deactivated.\"" >&6
+  echo "$as_me:$LINENO: result: MPI I/O symbols not found.  MPI I/O reporting deactivated." >&5
+echo "${ECHO_T}MPI I/O symbols not found.  MPI I/O reporting deactivated." >&6
 HAVE_MPI_IO=/dev/null
 
 fi
